### PR TITLE
test: test unix addrs

### PR DESCRIPTION
**Pull request by Stebalien**

### CODE REVIEW

**Comment by djdv** [comment]
These test are only being run on Linux, they fail on Windows.
```
--- FAIL: TestFromUnix (0.00s)
    convert_test.go:19: failed to convert: /unix/c:/foo/bar != /unix/\c:\foo\bar
--- FAIL: TestUnixSockets (0.00s)
    net_test.go:92: listen unix /C:\Users\DOMINI~1\AppData\Local\Temp\manettest213534587\listen.sock: bind: An invalid argument was supplied.
```

I'm seeing similar behavior even with same slashed paths, in the 9P branch.

```
10:33:05.029 ERROR plugin/fil: 9P listen error: listen unix /t:/ipfs/filesystem.9p.sock: bind: An invalid argument was supplied.
 filesystem.go:102

Error: listen unix /t:/ipfs/filesystem.9p.sock: bind: An invalid argument was supplied.
```

**Comment by Stebalien** [comment]
Hm. We really need to get windows tests working. Could you test it now?

**Comment by djdv** [comment]
Better, but not best. The string seems to be converted correctly, but we still need to see where/why this is failing with a seemingly correct argument.
```
--- FAIL: TestToUnix (0.00s)
    convert_test.go:43: naddr.Address() == \c:\foo\bar != /c:/foo/bar
--- FAIL: TestUnixSockets (0.00s)
    net_test.go:92: listen unix \C:\Users\DOMINI~1\AppData\Local\Temp\manettest809459775\listen.sock: bind: An invalid argument was supplied.
FAIL
exit status 1
FAIL    github.com/multiformats/go-multiaddr-net        0.086s
```

**Comment by djdv** [comment]
I'm wondering if the leading slash is being passed to something, or if that's just the target component of the multiaddr being returned in an error. `\C:\` vs `C:\` is going to cause problems.

We can either add logic to detect and strip this, or potentially use UNC path syntax `\\?\...` if this is valid in the WINAPI for UDS targets.

**Comment by Stebalien** [comment]
> I'm wondering if the leading slash is being passed to something, or if that's just the target component of the multiaddr being returned in an error. 

The leading slash is coming from the multiaddr. We start with `/unix/c:/foobar`, extract `/c:/foobar`, then convert the slashes to `\c:\foobar` (using `filepath.FromSlash`). We should probably just replace the leading `\` with `\\?\` on windows.

**Comment by djdv** [comment]
Attempting to upgrade the addr string to a UNC path did not seem to resolve this.
I'm wondering where these shortpaths (see: anno `DOMINI~1`) are coming from and if they're the actual source of the issue.
```
--- FAIL: TestUnixSockets (0.00s)
    net_test.go:99: path:\\?\C:\Users\DOMINI~1\AppData\Local\Temp\manettest945165231\listen.sock
    net_test.go:100: listen unix \\\?\C:\Users\DOMINI~1\AppData\Local\Temp\manettest945165231\listen.sock: bind: An invalid argument was supplied.
``

**Comment by djdv** [comment]
@Stebalien I don't have push permissions for this repo
This appears to fix the underlying issue.

```
>git diff HEAD~
diff --git a/convert.go b/convert.go
index 1f936e6..1c006a9 100644
--- a/convert.go
+++ b/convert.go
@@ -4,6 +4,7 @@ import (
        "fmt"
        "net"
        "path/filepath"
+       "runtime"

        ma "github.com/multiformats/go-multiaddr"
 )
@@ -143,6 +144,10 @@ func DialArgs(m ma.Multiaddr) (string, string, error) {
                        case ma.P_UNIX:
                                network = "unix"
                                ip = c.Value()
+                               // strip leading multiaddr slash
+                               if runtime.GOOS == "windows" {
+                                       ip = ip[1:]
+                               }
                                return false
                        }
                case "ip4":
```

**Comment by Stebalien** [comment]
@djdv I think I've fixed the tests. I've also added you to the org.

**Comment by djdv** [comment]
The compare string was being escaped, I used a backtick to preserve the literal `\`.
And also changed the drive letter to a capital 'C' to match api-native input.

**Comment by Stebalien** [comment]
Thanks!

**Comment by Stebalien** [comment]
Thanks!

**Pull request merged**
