### PR TITLE
Fix travis builds not supporting ipv6 by default anymore

### PR DESCRIPTION
**Pull request by hsanjuan**
License: MIT
Signed-off-by: Hector Sanjuan <code@hector.link>

### CODE REVIEW

**Comment by Stebalien** [comment]
Actually, all you need to do is set `sudo: true`. The standard CI script now takes care of the rest.

**Comment by hsanjuan** [comment]
that makes no sense, but ok

**Comment by hsanjuan** [comment]
@Stebalien that doesn't work https://travis-ci.org/multiformats/go-multiaddr-net/builds/333480923?utm_source=github_status&utm_medium=notification

**Comment by Stebalien** [comment]
Ah! The issue is that this repo doesn't *use* our standard scripts. I'll fix that.

As for what `sudo: true` does..., it allows os to, as root, enable proper IPv6 support: https://github.com/ipfs/ci-helpers/blob/master/travis-ci/run-standard-tests.sh#L31. We don't bother with an explicit "enable ipv6" flag because we *always* want it enabled if we have root. Unfortunately, travis disables it by default...

**Comment by Stebalien** [comment]
See #35.

**Comment by hsanjuan** [comment]
Sorry, when you said `standard CI script` I understood some travis stardard thing. I did not know that we had our own CI script as shown in the other PR.

**Pull request closed without merging**
