### PR TITLE
WIP: Add UDP support

### PR DESCRIPTION
**Pull request by lgierth**
Comments are very welcome. I haven't quite wrapped my head around the type wrapping, so it might be all wrong.

This essentially adds wrappers for net.PacketConn and net.ListenUDP().

### CODE REVIEW

**Comment by lgierth** [comment]
cc @Kubuxu

**Comment by lgierth** [comment]
Closing in favor of #23

**Comment by Kubuxu** [comment]
You have referenced the same issue.

**Comment by lgierth** [comment]
Ah thanks, I meant #24

**Pull request closed without merging**
