### PR TITLE
Add "ip6%" multiaddr support (IPv6 with zone ID)

### PR DESCRIPTION
**Pull request by mwnx**
Notes:

- I was not able to add a listen test (in TestListenAddrs) for ip6%
  addresses with a zone ID (e.g. fe80::1%eth0) since there is no
  guarantee that there will even be such a link-local address on the
  machine running the test, as would be the case if the machine had only
  a loopback address for instance.

- Regarding the IsIPLoopback function: I did not add an ip6% analog to
  the IP6LinkLocalLoopback case since I believe the existing case to be
  invalid (does not conform to any standard) and do not think the
  addition of a zone ID would make it any more valid. fe80::1%lo0 is
  used as a loopback address on Mac OS systems but can this be
  guaranteed? Even if it were guaranteed on Mac OS systems, the case
  would have to be made Mac OS specific.

---

See:
- https://github.com/multiformats/multiaddr/pull/68
- https://github.com/multiformats/go-multiaddr/pull/69

### CODE REVIEW

**Comment by Stebalien** [comment]
Let's finish https://github.com/multiformats/go-multiaddr-net/pull/40 first (so we can get those questions nailed down).

**Comment by Stebalien** [comment]
So, I just merged #47 which partially adds zone support. However, *it* allows an arbitrary number of zones *and* allows zones to prefix IP4 addrs. That's probably incorrect.

@vyzo could you find some time to get this merged/fixed?

**Comment by vyzo** [comment]
sure!

**Comment by mwnx** [comment]
On Thu, Oct 18, 2018 at 02:25:10PM +0000, vyzo wrote:
> @mwnx can you rebase and resolve the conflicts?

Sure. I'll try and get round to it within 24 hours.

-- 
mwnx
GPG: AEC9 554B 07BD F60D 75A3  AF6A 44E8 E4D4 0312 C726

**Comment by mwnx** [comment]
Just force-pushed a "merge" commit. See commit message for details.

-- 
mwnx
GPG: AEC9 554B 07BD F60D 75A3  AF6A 44E8 E4D4 0312 C726

**Comment by mwnx** [comment]
On Sun, Oct 21, 2018 at 03:00:26AM -0700, vyzo wrote:
> Can you `go fmt` as well? travis fails with complaints about formatting.

Sorry about that. Just fixed it.

-- 
mwnx
GPG: AEC9 554B 07BD F60D 75A3  AF6A 44E8 E4D4 0312 C726

**Comment by vyzo** [comment]
I think we re handling zones incorrectly in the `IsPublicAddr` and `IsPrivateAddr`. 

These functions should check that the address in the zone is public or private respectively, but we currently incorrectly return true in both cases:
https://github.com/multiformats/go-multiaddr-net/blob/master/private.go#L74
https://github.com/multiformats/go-multiaddr-net/blob/master/private.go#L95

Do you mind fixing those as well as part of this PR?

**Comment by vyzo** [comment]
Ah nevermind, the code falls back to the encapsulated address and is correct.

**Pull request merged**
