### PR TITLE
support udt listening and dialing

### PR DESCRIPTION
**Pull request by whyrusleeping**
vendor udt with gx

### CODE REVIEW

**Comment by jbenet** [comment]
Ugh, idk how i feel about ingesting 20k lines of c++ into this repo. 

see https://github.com/jbenet/go-multiaddr-net/issues/7 maybe we should do that now?

**Comment by whyrusleeping** [comment]
Yeah, i definitely agree pulling 20k lines of C++ into this would suck...

I was considering just translating the c++ code into go. It doesnt really do any weird hacks that would be difficult in go, so i'm thinking it would be a fairly clean translation. (thats not to say I dont want to do #7, just saying i'm dreading the cplusplocalypse)

**Comment by jbenet** [comment]
What about UTP and QUIC and BLE? Writing everything in Go is not tenable in the long run.

That said, i've an idea: we _could_ put these in a separate process: 
- make separate procs that handle an exotic Swarm transport (inc multiple conns), 
- pipes it all through unix pipe, or even just stdio, to `ipfs` bin.
- need a simple protocol to mux everything and let `ipfs` do the "accept/open stream"

**Comment by hsanjuan** [comment]
@whyrusleeping do you want to close this maybe?

**Pull request closed without merging**
