### PR TITLE
private networks and utility functions

### PR DESCRIPTION
**Pull request by vyzo**
extracted from go-libp2p-autonat

### CODE REVIEW

**Comment by raulk** [comment]
Heads-up, I'm working on the `Routability()` logic that we discussed on https://github.com/libp2p/go-libp2p/issues/436#issuecomment-424749758, which overlaps with this PR. Probably worth until I'm done with that because I'm also taking into consideration reserved and special purpose addresses.

**Comment by raulk** [comment]
Here's where I'm headed: https://github.com/raulk/go-multiaddr-net/commit/5630917eb09cf447df8e436733dba679f7197d05

I need to finishing populating the segment tables (using rfc6890 as a reference) and write tests. 

Feel free to proceed with this PR if it's urgent. I'd be done today with `Routability()` anyway.

**Comment by vyzo** [comment]
I think we can extend `IsPublicAddr` to take into account all non-routable addrs.
`IsPrivateAddr` is fine only checking the private networks.

**Comment by vyzo** [comment]
Added all the unroutable address ranges in the `IsPublicAddr` test

**Comment by raulk** [comment]
Multicast ranges added in the `SpecialPurpose` segment: https://github.com/raulk/go-multiaddr-net/blob/routability/routability.go

Next step is to treat IPv4-IPv6 translation ranges properly.

**Pull request merged**
